title:  Greg Holden
logo: assets/Greg Holden.jpeg 
description:  Capital Markets and Corporate Finance Specialist With Masters-Level Data Science Skills
show_downloads: false
theme: jekyll-theme-minimal
